name: Build Configurator

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches:
      - master
      - development
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build
  Build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Setup toolchain
      - name: Setup environment
        run: |
          pip install -r requirements.txt pyinstaller

      - name: Build Pyinstaller
        run: |
          pyinstaller ${{ github.workspace }}/build/OpenFFBoard.spec


      - uses: actions/upload-artifact@v2
        with:
          name: OpenFFBoard-Configurator-${{ matrix.os }}
          path: ${{ github.workspace }}/dist/
          if-no-files-found: error

 
