name: Build Windows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: build/OpenFFBoard.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Configurator
        path: build/dist # or path/to/artifact
